"""Now sso_id AND sso_provider are unique

Revision ID: aa7e2f69b0bd
Revises: def8cf373244
Create Date: 2025-04-08 15:28:00.272069

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa7e2f69b0bd"
down_revision: Union[str, None] = "def8cf373244"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("sso_provider", sa.String(), nullable=True)
    )
    op.drop_constraint("uq_users_sso_id", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_users_sso_id_sso_provider"),
        "users",
        ["sso_id", "sso_provider"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_users_sso_id_sso_provider"), "users", type_="unique"
    )
    op.create_unique_constraint("uq_users_sso_id", "users", ["sso_id"])
    op.drop_column("users", "sso_provider")
    # ### end Alembic commands ###
